version: '3.5'

services:

  php:
    build: ./php
    restart: always

  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306

  phpmyadmin:
    build: ./phpmyadmin
    restart: always
    ports:
      - 8080:80