version: '3.5'

services:


  web:
    build: ./nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./../:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./php
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    links:
      - maildev

  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306

  phpmyadmin:
    build: ./phpmyadmin
    restart: always
    ports:
      - 8080:80


  maildev:
    image: djfarrelly/maildev
    ports:
      - 8081:80