version: '3.5'

services:

  web:
    build: ./php
    restart: always
    ports:
      - 8888:80
#    environment:
#      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ./../:/var/www
      - ./php/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: feelback
      DB_USERNAME: feelback
      DB_PASSWORD: secret

  db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: feelback
      MYSQL_USER: feelback
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306

  phpmyadmin:
    build: ./phpmyadmin
    restart: always
    ports:
      - 8080:80
